#!/bin/bash

echo "Setting up Productive Environment" && echo "Starting Visual Studio Code"
code && echo "Starting Firefox with suitable tabs"
firefox github.com gmail.com google.com soundcloud.com/you/library https://www.youtube.com/
